version: "3.8"
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db
      JWT_SECRET: 560e309fd8ba17a6cb3aa2927cd3f46dfd85facfbacf1e03a363aca81bf18d09
      PORT: 5000
    ports:
      - "5002:5000"
    networks:
      - app-network

  login-user:
    build: ./login-user
    container_name: login-user
    restart: always
    depends_on:
      - auth-service
    environment:
      REACT_APP_API_URL: http://localhost:5002
    ports:
      - "3002:80"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # Port pour les messages AMQP
      - "15672:15672" # Port pour l'interface d'administration
    networks:
      - app-network
    

volumes:
  mariadb_data:


networks:
  app-network:
    driver: bridge


 
